version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=movie_dev
    networks:
      - dev-network
  test-db:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=movie_dev
    networks:
      - dev-network
networks:
  dev-network:
    